### ISSUE TITLE
Broken datasets

### ISSUE THREAD

**Issue by grigorios-oikonomou** [justinbois/fish-activity#8] opened 2017-03-31 19:48 UTC
Sometimes we need to stop an experiment because the plate has slightly shifted and needs to be re-aligned with the camera. That takes about 5min. Then we start the experiment again. The time lost is not critical when graphing/analyzing 60min bins. In this case we end with multiple .xls files that we name like this:

140421_3A_3B.XLS
140421_3Ap_3Bp.XLS
140421_3App_3Bpp.XLS

After running the perl script it is easy to fuse them (just paste one below the other in order). This is feasible because the matlab script will use the last "clock" column to determine time. I don't think that work with the .xls (or .csv) files in your software since you use the start time ( 0...60, 60...120, etc.) which is reset every time a recording starts. Do you think you can work around that? 

Ideally the partial files would be fused to a single .csv file that then can be run through the normal pipeline. Since you already made your software compatible with the output of the perl script, this is not a pressing issue; people can use that with your tools. However, I am guessing then we will lose much of the validation you have implemented. I will send you the broken datasets if you feel like playing with that.

**Comment by justinbois** [comment] 2017-03-31 20:01
This is also not a problem. We can use the time stamps to align the files in time.

**Comment by grigorios-oikonomou** [comment] 2017-03-31 20:05
OK, this is hilarious. It's like I am trying to come up with a problem and you are telling me to chill down, it's all gonna be fine  :)

**Comment by justinbois** [comment] 2017-07-28 23:20
Needed: @grigorios-oikonomou, can you please send me examples of this.

**Comment by justinbois** [comment] 2017-07-29 00:12
Signature of `load_activity` is:

```python
def load_activity(fname, genotype_fname, lights_on='9:00:00',
                  lights_off='23:00:00', day_in_the_life=4,
                  wake_threshold=1e-5, extra_cols=[],
                  rename={'middur': 'activity'}, comment='#',
                  gtype_double_header=None, gtype_rstrip=False)
```

If `fname` is a list or tuple, then those are separate files from the same experiment and need to be merged together. The issue is that experimental time and zeitgeber time need to be recomputed upon restart.

Also check to make sure we can handle resampling with missing data.

**Comment by grigorios-oikonomou** [comment] 2017-07-29 17:34
I send you example datasets through the caltech dropbox.

**Comment by justinbois** [comment] 2017-09-16 00:15
This is now implemented for loading in data sets, but there is a problem with resampling. Specifically, we now have missing data, and resampling with missing data can be tricky. E.g., what if we are resampling with a new new period of 5 minutes, but there are more then five minutes without data?

There is still also the issue of resampling using the experimental time (as given by the `start` column in the raw data set) or using the clock time. I suspect the clock time is actually more accurate, but, again, it is not uniform because of the occasional errors where the instrument does not quite get the data stored as fast as it should. Resampling across the gap is also an issue if we are using experimental time.

I think the best (most robust, but also happens to be fastest, I think) is to resample over the clock time using Pandas's built-in resamplers. We would still do the same resampling: the sum of activity levels over a 10-minute interval, for example, but the intervals would be strictly determined by the wall clock time. @grigorios-oikonomou, what do you think?

**Comment by justinbois** [comment] 2017-09-16 15:54
Another issue is partial minutes. For example, if we start an experiment at 14:06:15 and we program lights on to start at 9:00:00, then there is a 15 second overlap in a time where the lights switched on. One scheme of resampling is to resample over whole-minute intervals, where fractions of minutes are counted proportionally toward neighboring intervals. So, we could do a time shift, where the activity for the activity for interval 15:10:00 - 15:11:00:

(activity on interval 15:09:15-15:10:15) * 0.25 + (activity on interval 15:10:15-15:11:15) * 0.75

The problem with this, is that you still get the influence of the light coming on.

In light of this, I think we should continue resampling the way we have been with a small tweak for broken/multiple data sets.

1. Specify a resampling window in terms of number of measurements. Any errors in the resampling this way are due to the instrument not keeping up.
2. Resample over cycles. That is, have boundaries when the light goes on or off.
3. Have an added column to the DataFrame, "acquisition" which is an integer specifying which acquisition is being used.

There is no perfect answer to this, unfortunately, I think.

**Comment by justinbois** [comment] 2017-09-16 20:35
This is done. Important notes:

1. Still need to do rigorous unit testing when we have more than one input file.
2. Resampling and bout calculations never span across data sets. That is, if an acquisition was interrupted, all averaging, etc., does not span across the interruption.
3. Zeitgeber time is based off of the **clock**. This is the only way to get the data sets timed correctly.
4. Validation of the activity files still needs to be done on each individual file.

**Closed as completed by justinbois** 2017-09-16 20:35 UTC
Labels: help wanted
